LIBS := $(shell PATH=/home/elettra/root/bin:$$PATH root-config --libs) 
INCS := $(shell PATH=/home/elettra/root/bin:$$PATH root-config --cflags)

all: esercizio3.2.cc funzioni.h
	g++ esercizio3.2.cc -o esercizio3.2 ${INCS} ${LIBS} 
