LIBS := $(shell PATH=/home/elettra/root/bin:$$PATH root-config --libs) 
INCS := $(shell PATH=/home/elettra/root/bin:$$PATH root-config --cflags)

all: esercizio8.0.cc VectorOperations.h
	g++ -o esercizio8.0 esercizio8.0.cc 

